### ISSUE TITLE
Sending custom alert to two different groups returns SQL error page

### ISSUE THREAD

**Issue by echogit** [MyAlerts/Custom-Alerts-for-MyAlerts#5]
Using latest version of both custom alerts and alerts. When sending custom alerts to two different groups it returns error, the alert doesn't work:

ERROR MESSAGE:
MyBB SQL Error
MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '','4','6))' at line 5
Query:
SELECT a.user_id FROM mybb_alert_setting_values a LEFT JOIN mybb_users u ON (a.user_id = u.uid) LEFT JOIN mybb_alert_settings s ON (a.setting_id = s.id) WHERE s.code = 'custom' AND a.value <> 0 AND (u.usergroup IN (3','4','6))

**Comment by echogit** [comment]
BTW, it works fine if you choose only one group.

**Comment by Shade-** [comment]
Stupid typo:

```
$usergroups = implode("','", $usergroups);
$usergroups = "usergroup IN ({$usergroups})";
```

That's what caused the usergroups to be listed with wrong quotes and therefore output a SQL error. Noticed that usergroups are actually integers, so we can implode the array without escaping every value (since SQL language accepts integers values separated by a coma in a WHERE clause).
